<a href="https://colab.research.google.com/github/tanushri1712/tanushri1712/blob/main/dwt_randomforest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Libraries

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# *Data after DWT Feature Extraction* 

In [ ]:
df = pd.read_csv('dwt.csv', header=None, delimiter=',', quotechar='"')
df.head() 

0    1      2      3      4   ...            37     38     39      40       41
0   0 -5.0  1.436  1.434  1.441  ... -3.540000e-17 -0.015 -0.025 -0.0325 -0.09875
1   0 -5.0  1.436  1.434  1.441  ...  3.540000e-17 -0.015 -0.025 -0.0325 -0.09875
2   0 -5.0  1.432  1.434  1.441  ... -1.000000e-02  0.015 -0.025 -0.0325 -0.09875
3   0 -5.0  1.432  1.434  1.441  ...  1.000000e-02  0.015 -0.025 -0.0325 -0.09875
4   0 -5.0  1.444  1.448  1.441  ... -1.000000e-02 -0.015  0.025 -0.0325 -0.09875

[5 rows x 42 columns]

In [ ]:
# adding column name to the respective columns
df.columns =['Target','Time', 'ba1', 'ba2','ba3','ba4','ba5','bd1', 'bd2','bd3','bd4','bd5','ca1','ca2','ca3','ca4','ca5', 'cd1', 'cd2','cd3','cd4','cd5','da1','da2','da3','da4','da5','dd1','dd2','dd3','dd4','dd5','ea1','ea2','ea3','ea4','ea5','ed1','ed2','ed3','ed4','ed5']
  
# displaying the DataFrame
print(df)

      Target  Time    ba1  ...           ed3           ed4           ed5
0          0 -5.00  1.436  ... -2.500000e-02 -3.250000e-02 -9.875000e-02
1          0 -5.00  1.436  ... -2.500000e-02 -3.250000e-02 -9.875000e-02
2          0 -5.00  1.432  ... -2.500000e-02 -3.250000e-02 -9.875000e-02
3          0 -5.00  1.432  ... -2.500000e-02 -3.250000e-02 -9.875000e-02
4          0 -5.00  1.444  ...  2.500000e-02 -3.250000e-02 -9.875000e-02
...      ...   ...    ...  ...           ...           ...           ...
3646       3 -4.03  1.408  ...  1.750000e-02  4.000000e-02  7.750000e-02
3647       3 -4.03  1.408  ...  1.750000e-02  4.000000e-02  7.750000e-02
3648       3 -4.03  1.396  ... -3.660000e-17 -2.260000e-18 -4.130000e-18
3649       3 -4.03  1.396  ... -3.660000e-17 -2.260000e-18 -4.130000e-18
3650       3 -4.03  1.384  ... -3.660000e-17 -2.260000e-18 -4.130000e-18

[3651 rows x 42 columns]


# Scaling

In [ ]:
from sklearn import decomposition, datasets
from sklearn.preprocessing import StandardScaler

In [ ]:

std_slc = StandardScaler()
X_std = std_slc.fit_transform(df)

print(X_std.shape)
print(X_std)

(3651, 42)
[[-1.61432034e+00 -2.22676465e+00 -1.63829706e+00 ... -8.52080534e-01
  -5.40382361e-01 -8.53410074e-01]
 [-1.61432034e+00 -2.22676465e+00 -1.63829706e+00 ... -8.52080534e-01
  -5.40382361e-01 -8.53410074e-01]
 [-1.61432034e+00 -2.22676465e+00 -1.67425456e+00 ... -8.52080534e-01
  -5.40382361e-01 -8.53410074e-01]
 ...
 [-2.05173217e-02  2.60797635e-01 -1.99787207e+00 ... -1.24642088e-15
  -3.71981501e-17 -3.51663935e-17]
 [-2.05173217e-02  2.60797635e-01 -1.99787207e+00 ... -1.24642088e-15
  -3.71981501e-17 -3.51663935e-17]
 [-2.05173217e-02  2.60797635e-01 -2.10574458e+00 ... -1.24642088e-15
  -3.71981501e-17 -3.51663935e-17]]


# PCA

In [ ]:
    pca = decomposition.PCA(n_components=4)

    X_std_pca = pca.fit_transform(X_std)

    print(X_std_pca.shape)
    print(X_std_pca)

(3651, 4)
[[ 5.06192178 -1.18607594  0.99996902  2.01378333]
 [ 5.0619308  -1.18606305  0.99988354  2.01565898]
 [ 5.07646985 -1.14648096  1.03788332  2.26628138]
 ...
 [ 5.72060573 -0.41304736  2.00082982 -0.4490796 ]
 [ 5.72072982 -0.41287097  2.00027328 -0.4289078 ]
 [ 5.74794618 -0.4077165   2.06391219 -0.31914737]]


# FEATURE SELECTION BY RF

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split

In [ ]:
#Checking if any columns have missing values
df.columns[df.isna().any()]

Index([], dtype='object')

In [ ]:
#Importing Random Forest and feature selection libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
X = df.drop('Target',axis=1)
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X_std_pca, y, test_size=0.33, random_state=42)

In [ ]:
#calculating accuracy with all features
from sklearn.metrics import accuracy_score
clf = RandomForestClassifier(n_estimators=1000, random_state=0, n_jobs=-1)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.9219917012448133

In [ ]:

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       156
           1       0.94      0.91      0.92       119
           2       0.88      0.86      0.87       189
           3       0.91      0.94      0.93       351
           4       0.91      0.81      0.86        93
           5       0.88      0.87      0.88        85
           6       0.94      0.97      0.95       212

    accuracy                           0.92      1205
   macro avg       0.92      0.91      0.91      1205
weighted avg       0.92      0.92      0.92      1205



In [ ]:
#Using selectFromModelto choose the most important features
#Setting threshold as 0.02

sel = SelectFromModel(RandomForestClassifier(n_estimators = 1000),threshold = 0.02)
sel.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(n_estimators=1000),
                threshold=0.02)

In [ ]:
#Printing the boolean values of the important columns
sel.get_support()

array([ True,  True,  True,  True])

In [ ]:
selected_features

Index(['Time', 'ba4', 'ba5', 'bd5', 'ca4', 'ca5', 'cd5', 'da4', 'da5', 'dd5',
       'ea4', 'ea5', 'ed5'],
      dtype='object')

In [ ]:
X = df[selected_features]
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


#fitting the model with the most importart features
clf2 = RandomForestClassifier(n_estimators=1000, random_state=0, n_jobs=-1)
clf2.fit(X_train, y_train)
y_pred = clf2.predict(X_test)
accuracy_score(y_test, y_pred)

0.9966804979253112

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       156
           1       1.00      1.00      1.00       119
           2       0.98      1.00      0.99       189
           3       1.00      0.99      1.00       351
           4       0.99      1.00      0.99        93
           5       1.00      0.99      0.99        85
           6       1.00      1.00      1.00       212

    accuracy                           1.00      1205
   macro avg       1.00      1.00      1.00      1205
weighted avg       1.00      1.00      1.00      1205

